# -*- coding: utf-8 -*-
"""collecting-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IVk1eQ9dy6MYg7mdMWg_OWmSlrv1V6-
"""

import yfinance as yf
import pandas as pd
def fetch_data(ticker, start_date=None, end_date=None, interval='1d'):
    """
    Fetches OHCLV stock data and drops missing values
    """
    # Fetch the data
    stock = yf.Ticker(ticker)
    ohlcv_df = stock.history(start=start_date, end=end_date, interval=interval)

    # Remove rows with any missing values
    ohlcv_df_clean = ohlcv_df.dropna()

    # Uncomment below to print the data
    #print(stock.financials)
    #print(stock.balance_sheet)
    #print(stock.cashflow)
    return ohlcv_df_clean

#JPM JNJ PG XOM
#fetch_data(ticker, start_time, end_time)
data = fetch_data("KO", "2020-01-01", "2024-12-31")
data.head()

import requests

# The code below requires an API Key which can be generated from the url below. I believe the api allows
# like 1000 requests per month
def fetch_news_articles(ticker,from_date=None, to_date=None, language='en', page_size=100):

    url = 'https://newsapi.org/v2/everything'
    params = {
        'q': ticker,
        'apiKey': "INSERT YOUR API KEY HERE!!!",
        'language': language,
        'pageSize': page_size,
        'from': from_date,
        'to': to_date,
        'sortBy': 'relevancy'
    }

    response = requests.get(url, params=params)

    data = response.json()

    if data.get('status') == 'ok':
        articles = data.get('articles', [])
        news_df = pd.DataFrame(articles)[['publishedAt', 'title', 'description', 'url', 'content']]
        news_df['publishedAt'] = pd.to_datetime(news_df['publishedAt'])
        return news_df
    else:
        raise Exception(f"Error fetching news: {data.get('message', 'Unknown error')}")

# Only works up to a month back, currently only returns the title and description of articles in a pd
# dataframe. Will probably be updated soon
news_df = fetch_news_articles("GOOG", "2025-01-06", "2025-02-06")

print(news_df)